import { eq, type Sql, sql } from "durcno";
import {
  db,
  type Events,
  Logs,
  NetworkDevices,
  Posts,
  UserProfiles,
  Users,
} from "./schema";
import { type Equal, Expect } from "./utils";

// ============================================================================
// Section 1: Column Insert Type Inference (Static Type Assertions)
// ============================================================================

type UsersInsertType = Parameters<
  ReturnType<typeof db.insert<typeof Users>>["values"]
>[0] extends (infer T)[] | object
  ? T
  : never;

type UserProfilesInsertType = Parameters<
  ReturnType<typeof db.insert<typeof UserProfiles>>["values"]
>[0] extends (infer T)[] | object
  ? T
  : never;

type EventsInsertType = Parameters<
  ReturnType<typeof db.insert<typeof Events>>["values"]
>[0] extends (infer T)[] | object
  ? T
  : never;

type LogsInsertType = Parameters<
  ReturnType<typeof db.insert<typeof Logs>>["values"]
>[0] extends (infer T)[] | object
  ? T
  : never;

// Primary key / Generated ALWAYS column should be excluded from insert payload
Expect<Equal<"id" extends keyof UsersInsertType ? true : false, false>>();

// Generated BY DEFAULT column should be optional (value | undefined | Sql)
Expect<Equal<UserProfilesInsertType["id"], number | undefined | Sql>>();

// Not null column without default should be required (value | Sql)
Expect<Equal<UsersInsertType["username"], string | Sql>>();

// Not null column with default should be optional (value | undefined | Sql)
Expect<Equal<UsersInsertType["createdAt"], Date | undefined | Sql>>();

// Default column without not null should allow value | null | undefined | Sql
Expect<
  Equal<EventsInsertType["description"], string | null | undefined | Sql>
>();

// Nullable column without default should allow value | null | undefined | Sql
Expect<Equal<UsersInsertType["email"], string | null | undefined | Sql>>();

// Column with $insertFn should be optional due to insertFn default
Expect<Equal<LogsInsertType["createdAt"], Date | undefined | Sql>>();

// ============================================================================
// Section 2: Values Input & Query Builder Types
// ============================================================================

// Single row insert
db.insert(Users).values({
  username: "ghost",
  email: "email@example.com",
  type: "admin",
  externalId: "550e8400-e29b-41d4-a716-446655440000",
});

// Multi-row insert with optional/nullable array column
db.insert(Posts).values([
  {
    userId: 1n,
    title: "title",
    content: "content",
    tags: ["typescript", "postgres"],
  },
  {
    userId: 1n,
    title: "title",
    tags: null,
  },
]);

// Column with $insertFn default vs explicit value override
db.insert(Logs).values({
  message: "Log message",
  updatedAt: new Date(),
});

db.insert(Logs).values({
  message: "Log message with explicit createdAt",
  createdAt: new Date(),
  updatedAt: new Date(),
});

// Sql expression in insert values
db.insert(Users).values({
  username: sql`LOWER('ghost')`,
  type: "user",
  externalId: "550e8400-e29b-41d4-a716-446655440000",
});

// Column with $type override
db.insert(Posts).values({
  userId: 1n,
  title: "Metrics Post",
  metrics: { views: 100, likes: 50 },
});

// Bytea and Network address types
db.insert(UserProfiles).values({
  userId: 1n,
  avatarData: Buffer.from("avatar"),
});

db.insert(NetworkDevices).values({
  name: "Router",
  ipAddress: "192.168.1.1",
  networkRange: "192.168.0.0/24",
  macAddress: "00:11:22:33:44:55",
});

// ============================================================================
// Section 3: Returning Clause Selection
// ============================================================================

// Specific column selection returning
const _insertReturningSpecific = db
  .insert(Users)
  .values({
    username: "ghost",
    type: "user",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  .returning({ id: true, username: true, email: true });
type InsertReturningSpecific = Awaited<typeof _insertReturningSpecific>;
Expect<
  Equal<
    InsertReturningSpecific,
    { id: bigint; username: string; email: string | null }[]
  >
>();

// False-map returning ({ column: false }) excludes specified column
const _insertReturningFalseMap = db
  .insert(Users)
  .values({
    username: "ghost",
    type: "user",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  .returning({ email: false });
type InsertReturningFalseMap = Awaited<typeof _insertReturningFalseMap>;
Expect<
  Equal<
    InsertReturningFalseMap,
    {
      id: bigint;
      username: string;
      type: "admin" | "user";
      createdAt: Date;
      externalId: string;
      trackingId: string | null;
    }[]
  >
>();

// Wildcard returning ("*") single row
const _insertReturningWildcardSingle = db
  .insert(Users)
  .values({
    username: "ghost",
    type: "user",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  .returning("*");
type InsertReturningWildcardSingle = Awaited<
  typeof _insertReturningWildcardSingle
>;
Expect<
  Equal<
    InsertReturningWildcardSingle,
    {
      id: bigint;
      username: string;
      email: string | null;
      type: "admin" | "user";
      createdAt: Date;
      externalId: string;
      trackingId: string | null;
    }[]
  >
>();

// Wildcard returning ("*") multi row
const _insertReturningWildcardMulti = db
  .insert(Users)
  .values([
    {
      username: "user1",
      type: "user",
      externalId: "550e8400-e29b-41d4-a716-446655440000",
    },
    {
      username: "user2",
      type: "admin",
      externalId: "550e8400-e29b-41d4-a716-446655440001",
    },
  ])
  .returning("*");
type InsertReturningWildcardMulti = Awaited<
  typeof _insertReturningWildcardMulti
>;
Expect<
  Equal<
    InsertReturningWildcardMulti,
    {
      id: bigint;
      username: string;
      email: string | null;
      type: "admin" | "user";
      createdAt: Date;
      externalId: string;
      trackingId: string | null;
    }[]
  >
>();

// ============================================================================
// Section 4: OnConflict / Upsert Type Behavior
// ============================================================================

// doUpdateSet with set and where callbacks referencing excluded
const _upsertResult = db
  .insert(Users)
  .values({
    username: "alice",
    type: "user",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  .onConflict(Users.externalId)
  .doUpdateSet(
    ({ excluded }) => ({ username: excluded.username }),
    ({ excluded }) => eq(excluded.username, "alice"),
  )
  .returning({ id: true, username: true });
type UpsertResult = Awaited<typeof _upsertResult>;
Expect<Equal<UpsertResult, { id: bigint; username: string }[]>>();

// doNothing with returning
const _doNothingWithReturning = db
  .insert(Users)
  .values({
    username: "bob",
    type: "admin",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  .onConflict(Users.email)
  .doNothing()
  .returning({ id: true });
type DoNothingWithReturning = Awaited<typeof _doNothingWithReturning>;
Expect<Equal<DoNothingWithReturning, { id: bigint }[]>>();

// Targetless conflict doUpdateSet returns `never`
const _doUpdateSetNoTarget = db
  .insert(Users)
  .values({
    username: "alice",
    type: "user",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  .onConflict()
  .doUpdateSet(({ excluded }) => ({ username: excluded.username }));
type DoUpdateSetNoTarget = typeof _doUpdateSetNoTarget;
Expect<Equal<DoUpdateSetNoTarget, never>>();

// ============================================================================
// Section 5: Negative Type Safety Tests
// ============================================================================

// Cannot pass generated ALWAYS column
db.insert(Users).values({
  // @ts-expect-error - id is generated ALWAYS and excluded from insert type
  id: 1n,
  username: "ghost",
  type: "admin",
  externalId: "550e8400-e29b-41d4-a716-446655440000",
});

// @ts-expect-error - Missing required username field should not compile
db.insert(Users).values({ email: "email@example.com", type: "user" });

// Field value type mismatch
db.insert(Users).values({
  // @ts-expect-error - username should be string, not number
  username: 123,
  type: "admin",
  externalId: "550e8400-e29b-41d4-a716-446655440000",
});

// Invalid enum value
db.insert(Users).values({
  username: "ghost",
  // @ts-expect-error - invalid enum value
  type: "invalid_type",
  externalId: "550e8400-e29b-41d4-a716-446655440000",
});

// Non-existent column on table payload
db.insert(Users).values({
  // @ts-expect-error - postId does not exist on Users
  postId: 1,
  username: "test",
  type: "user",
  externalId: "550e8400-e29b-41d4-a716-446655440000",
});

// Mismatched $type override property
db.insert(Posts).values({
  userId: 1n,
  // @ts-expect-error - views in metrics should be a number, not string
  metrics: { views: "invalid", likes: 10 },
});

// Non-existent column in returning selection
db.insert(Users)
  .values({
    username: "test",
    type: "user",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  // @ts-expect-error - Returning non-existent column should not compile
  .returning({ nonExistentColumn: true });

// Invalid column reference on excluded in onConflict
db.insert(Users)
  .values({
    username: "alice",
    type: "user",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  .onConflict(Users.externalId)
  .doUpdateSet(
    // @ts-expect-error - nonExistent does not exist on excluded
    ({ excluded }) => ({ username: excluded.nonExistent }),
  );
