import { add, coalesce, count, eq, type InferInsert, lower, sql } from "durcno";
import {
  CheckTest,
  db,
  type Events,
  Logs,
  NetworkDevices,
  Posts,
  UserProfiles,
  Users,
} from "./schema";
import { type Equal, Expect } from "./utils";

// ============================================================================
// Section 1: Column Insert Value Type Inference (Static Type Assertions)
// ============================================================================

type UsersInsert = InferInsert<typeof Users>;
type UserProfilesInsert = InferInsert<typeof UserProfiles>;
type EventsInsert = InferInsert<typeof Events>;
type LogsInsert = InferInsert<typeof Logs>;

// Primary key / Generated ALWAYS column should be excluded from insert model
Expect<Equal<"id" extends keyof UsersInsert ? true : false, false>>();

// Primary key / Generated ALWAYS column should be excluded from insert values payload
type UsersInsertParams = Parameters<
  ReturnType<typeof db.insertInto<typeof Users>>["values"]
>[0] extends (infer T)[] | object
  ? T
  : never;
Expect<Equal<"id" extends keyof UsersInsertParams ? true : false, false>>();

// Generated BY DEFAULT column should be optional (value | undefined)
Expect<Equal<UserProfilesInsert["id"], number | undefined>>();

// Not null column without default should be required (value)
Expect<Equal<UsersInsert["username"], string>>();

// Not null column with default should be optional (value | undefined)
Expect<Equal<UsersInsert["createdAt"], Date | undefined>>();

// Default column without not null should allow value | null | undefined
Expect<Equal<EventsInsert["description"], string | null | undefined>>();

// Nullable column without default should allow value | null | undefined
Expect<Equal<UsersInsert["email"], string | null | undefined>>();

// Column with $insertFn should be optional due to insertFn default
Expect<Equal<LogsInsert["createdAt"], Date | undefined>>();

// ============================================================================
// Section 2: Values Input & Query Builder Types
// ============================================================================

// Single row insert
db.insertInto(Users).values({
  username: "ghost",
  email: "email@example.com",
  type: "admin",
  externalId: "550e8400-e29b-41d4-a716-446655440000",
});

// Multi-row insert with optional/nullable array column
db.insertInto(Posts).values([
  {
    userId: 1n,
    title: "title",
    content: "content",
    tags: ["typescript", "postgres"],
  },
  {
    userId: 1n,
    title: "title",
    tags: null,
  },
]);

// Column with $insertFn default vs explicit value override
db.insertInto(Logs).values({
  message: "Log message",
  updatedAt: new Date(),
});

db.insertInto(Logs).values({
  message: "Log message with explicit createdAt",
  createdAt: new Date(),
  updatedAt: new Date(),
});

// Sql expression in insert values
db.insertInto(Users).values({
  username: sql`LOWER('ghost')`,
  type: "user",
  externalId: "550e8400-e29b-41d4-a716-446655440000",
});

// Scalar SQL functions in insert values (no column references)
db.insertInto(Users).values({
  username: lower("ghost"),
  email: coalesce(null, "fallback@example.com"),
  type: "user",
  externalId: "550e8400-e29b-41d4-a716-446655440000",
});

db.insertInto(CheckTest).values({
  name: "check",
  price: 100n,
  quantity: add(1, 2),
});

// Column with $type override
db.insertInto(Posts).values({
  userId: 1n,
  title: "Metrics Post",
  metrics: { views: 100, likes: 50 },
});

// Bytea and Network address types
db.insertInto(UserProfiles).values({
  userId: 1n,
  avatarData: Buffer.from("avatar"),
});

db.insertInto(NetworkDevices).values({
  name: "Router",
  ipAddress: "192.168.1.1",
  networkRange: "192.168.0.0/24",
  macAddress: "00:11:22:33:44:55",
});

// ============================================================================
// Section 3: Returning Clause Selection
// ============================================================================

// Specific column selection returning
const _insertReturningSpecific = db
  .insertInto(Users)
  .values({
    username: "ghost",
    type: "user",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  .returning({ id: true, username: true, email: true });
type InsertReturningSpecific = Awaited<typeof _insertReturningSpecific>;
Expect<
  Equal<
    InsertReturningSpecific,
    { id: bigint; username: string; email: string | null }[]
  >
>();

// False-map returning ({ column: false }) excludes specified column
const _insertReturningFalseMap = db
  .insertInto(Users)
  .values({
    username: "ghost",
    type: "user",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  .returning({ email: false });
type InsertReturningFalseMap = Awaited<typeof _insertReturningFalseMap>;
Expect<
  Equal<
    InsertReturningFalseMap,
    {
      id: bigint;
      username: string;
      type: "admin" | "user";
      createdAt: Date;
      externalId: string;
      trackingId: string | null;
    }[]
  >
>();

// Wildcard returning ("*") single row
const _insertReturningWildcardSingle = db
  .insertInto(Users)
  .values({
    username: "ghost",
    type: "user",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  .returning("*");
type InsertReturningWildcardSingle = Awaited<
  typeof _insertReturningWildcardSingle
>;
Expect<
  Equal<
    InsertReturningWildcardSingle,
    {
      id: bigint;
      username: string;
      email: string | null;
      type: "admin" | "user";
      createdAt: Date;
      externalId: string;
      trackingId: string | null;
    }[]
  >
>();

// Wildcard returning ("*") multi row
const _insertReturningWildcardMulti = db
  .insertInto(Users)
  .values([
    {
      username: "user1",
      type: "user",
      externalId: "550e8400-e29b-41d4-a716-446655440000",
    },
    {
      username: "user2",
      type: "admin",
      externalId: "550e8400-e29b-41d4-a716-446655440001",
    },
  ])
  .returning("*");
type InsertReturningWildcardMulti = Awaited<
  typeof _insertReturningWildcardMulti
>;
Expect<
  Equal<
    InsertReturningWildcardMulti,
    {
      id: bigint;
      username: string;
      email: string | null;
      type: "admin" | "user";
      createdAt: Date;
      externalId: string;
      trackingId: string | null;
    }[]
  >
>();

// ============================================================================
// Section 4: OnConflict / Upsert Type Behavior
// ============================================================================

// doUpdateSet with set and where callbacks referencing excluded
const _upsertResult = db
  .insertInto(Users)
  .values({
    username: "alice",
    type: "user",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  .onConflict(Users.externalId)
  .doUpdateSet(
    ({ excluded }) => ({ username: excluded.username }),
    ({ excluded }) => eq(excluded.username, "alice"),
  )
  .returning({ id: true, username: true });
type UpsertResult = Awaited<typeof _upsertResult>;
Expect<Equal<UpsertResult, { id: bigint; username: string }[]>>();

// doUpdateSet with scalar SQL functions referencing table columns and excluded
db.insertInto(Users)
  .values({
    username: "alice",
    type: "user",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  .onConflict(Users.externalId)
  .doUpdateSet(({ excluded }) => ({
    username: lower(excluded.username),
    email: coalesce(Users.email, "fallback@example.com"),
  }));

db.insertInto(CheckTest)
  .values({ price: 100n, quantity: 10, name: "item" })
  .onConflict(CheckTest.id)
  .doUpdateSet(({ excluded }) => ({
    quantity: add(CheckTest.quantity, excluded.quantity),
    name: excluded.name,
  }));

// doUpdateSet with raw Sql
db.insertInto(Users)
  .values({
    username: "alice",
    type: "user",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  .onConflict(Users.externalId)
  .doUpdateSet(() => ({
    username: sql`'static_name'`,
  }));

// doNothing with returning
const _doNothingWithReturning = db
  .insertInto(Users)
  .values({
    username: "bob",
    type: "admin",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  .onConflict(Users.email)
  .doNothing()
  .returning({ id: true });
type DoNothingWithReturning = Awaited<typeof _doNothingWithReturning>;
Expect<Equal<DoNothingWithReturning, { id: bigint }[]>>();

// Targetless conflict doUpdateSet returns `never`
const _doUpdateSetNoTarget = db
  .insertInto(Users)
  .values({
    username: "alice",
    type: "user",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  .onConflict()
  .doUpdateSet(({ excluded }) => ({ username: excluded.username }));
type DoUpdateSetNoTarget = typeof _doUpdateSetNoTarget;
Expect<Equal<DoUpdateSetNoTarget, never>>();

// ============================================================================
// Section 5: Negative Type Safety Tests
// ============================================================================

// Cannot pass generated ALWAYS column
db.insertInto(Users).values({
  // @ts-expect-error - id is generated ALWAYS and excluded from insert type
  id: 1n,
  username: "ghost",
  type: "admin",
  externalId: "550e8400-e29b-41d4-a716-446655440000",
});

// @ts-expect-error - Missing required username field should not compile
db.insertInto(Users).values({ email: "email@example.com", type: "user" });

// Field value type mismatch
db.insertInto(Users).values({
  // @ts-expect-error - username should be string, not number
  username: 123,
  type: "admin",
  externalId: "550e8400-e29b-41d4-a716-446655440000",
});

// Invalid enum value
db.insertInto(Users).values({
  username: "ghost",
  // @ts-expect-error - invalid enum value
  type: "invalid_type",
  externalId: "550e8400-e29b-41d4-a716-446655440000",
});

// Non-existent column on table payload
db.insertInto(Users).values({
  // @ts-expect-error - postId does not exist on Users
  postId: 1,
  username: "test",
  type: "user",
  externalId: "550e8400-e29b-41d4-a716-446655440000",
});

// Mismatched $type override property
db.insertInto(Posts).values({
  userId: 1n,
  // @ts-expect-error - views in metrics should be a number, not string
  metrics: { views: "invalid", likes: 10 },
});

// Non-existent column in returning selection
db.insertInto(Users)
  .values({
    username: "test",
    type: "user",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  // @ts-expect-error - Returning non-existent column should not compile
  .returning({ nonExistentColumn: true });

// Invalid column reference on excluded in onConflict
db.insertInto(Users)
  .values({
    username: "alice",
    type: "user",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  .onConflict(Users.externalId)
  .doUpdateSet(
    // @ts-expect-error - nonExistent does not exist on excluded
    ({ excluded }) => ({ username: excluded.nonExistent }),
  );

// Negative test: db.insert does not exist; use db.insertInto
// @ts-expect-error - Property 'insert' does not exist on db; use insertInto
db.insert(Users);

// Column-referencing scalar function cannot be used in insert values
db.insertInto(Users).values({
  // @ts-expect-error - Column-referencing scalar function cannot be used in insert values
  username: lower(Users.username),
  type: "user",
  externalId: "550e8400-e29b-41d4-a716-446655440000",
});

// Aggregate SQL function cannot be used in insert values
db.insertInto(Users).values({
  // @ts-expect-error - Aggregate SQL function cannot be used in insert values
  username: count(Users.id),
  type: "user",
  externalId: "550e8400-e29b-41d4-a716-446655440000",
});

// Type mismatch: numeric scalar function cannot be assigned to string column
db.insertInto(Users).values({
  // @ts-expect-error - Type mismatch: numeric scalar function cannot be assigned to string column
  username: add(1, 2),
  type: "user",
  externalId: "550e8400-e29b-41d4-a716-446655440000",
});

// doUpdateSet rejects aggregate SQL function
db.insertInto(Users)
  .values({
    username: "alice",
    type: "user",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  .onConflict(Users.externalId)
  // @ts-expect-error - Aggregate SQL function cannot be used in doUpdateSet
  .doUpdateSet(() => ({ username: count(Users.id) }));

// doUpdateSet rejects column of another table
db.insertInto(Users)
  .values({
    username: "alice",
    type: "user",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  .onConflict(Users.externalId)
  // @ts-expect-error - Column of another table cannot be used in doUpdateSet
  .doUpdateSet(() => ({ username: Posts.title }));

// doUpdateSet rejects scalar function referencing another table
db.insertInto(Users)
  .values({
    username: "alice",
    type: "user",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  .onConflict(Users.externalId)
  // @ts-expect-error - Scalar function referencing another table cannot be used in doUpdateSet
  .doUpdateSet(() => ({ username: lower(Posts.title) }));

// doUpdateSet rejects type mismatch
db.insertInto(Users)
  .values({
    username: "alice",
    type: "user",
    externalId: "550e8400-e29b-41d4-a716-446655440000",
  })
  .onConflict(Users.externalId)
  // @ts-expect-error - Numeric scalar function cannot be assigned to string column
  .doUpdateSet(() => ({ username: add(1, 2) }));
