import {
  add,
  and,
  coalesce,
  count,
  eq,
  type InferUpdate,
  lower,
  sql,
} from "durcno";
import {
  CheckTest,
  db,
  type Events,
  Logs,
  Posts,
  UserProfiles,
  Users,
} from "./schema";
import { type Equal, Expect } from "./utils";

// ============================================================================
// Section 1: Column Update Value Type Inference (Static Type Assertions)
// ============================================================================

type UsersUpdate = InferUpdate<typeof Users>;
type EventsUpdate = InferUpdate<typeof Events>;
type LogsUpdate = InferUpdate<typeof Logs>;

// Primary key column should be excluded from update model
Expect<Equal<"id" extends keyof UsersUpdate ? true : false, false>>();

// Primary key column should be excluded from query builder update set object
type UsersSetParams = Parameters<
  ReturnType<typeof db.update<typeof Users>>["set"]
>[0];
Expect<Equal<"id" extends keyof UsersSetParams ? true : false, false>>();

// Generated BY DEFAULT column should be optional and allow bigint | null | undefined
Expect<Equal<EventsUpdate["autoId"], bigint | null | undefined>>();

// Not null column without default should be optional in update
Expect<Equal<UsersUpdate["username"], string | undefined>>();

// Not null column with default should be optional in update
Expect<Equal<UsersUpdate["createdAt"], Date | undefined>>();

// Default column without not null should allow value | null | undefined
Expect<Equal<EventsUpdate["description"], string | null | undefined>>();

// Nullable column without default should allow value | null | undefined
Expect<Equal<UsersUpdate["email"], string | null | undefined>>();

// Column with $updateFn should be optional in update
Expect<Equal<LogsUpdate["updatedAt"], Date | undefined>>();

// ============================================================================
// Section 2: Update Query Builder & Values (.set())
// ============================================================================

// Basic update returning null
const _basicUpdateQuery = db.update(Users).set({
  username: "new_username",
  email: "new@example.com",
});
type BasicUpdate = Awaited<typeof _basicUpdateQuery>;
Expect<Equal<BasicUpdate, null>>();

// Partial update (subset of columns)
const _partialUpdateQuery = db.update(Users).set({
  email: "updated@example.com",
});
type PartialUpdate = Awaited<typeof _partialUpdateQuery>;
Expect<Equal<PartialUpdate, null>>();

// Setting nullable field to explicit null
const _nullUpdateQuery = db.update(Users).set({
  email: null,
});
type NullUpdate = Awaited<typeof _nullUpdateQuery>;
Expect<Equal<NullUpdate, null>>();

// Setting optional field to explicit undefined
const _undefinedUpdateQuery = db.update(Users).set({
  username: "new_username",
  email: undefined,
});
type UndefinedUpdate = Awaited<typeof _undefinedUpdateQuery>;
Expect<Equal<UndefinedUpdate, null>>();

// Sql expression value in set
const _updateSqlValueQuery = db.update(Users).set({
  username: sql`LOWER(first_name)`,
});
type UpdateSqlValue = Awaited<typeof _updateSqlValueQuery>;
Expect<Equal<UpdateSqlValue, null>>();

// Column with $type override in set
const _updateMetricsQuery = db.update(Posts).set({
  metrics: { views: 200, likes: 100 },
});
type UpdateMetrics = Awaited<typeof _updateMetricsQuery>;
Expect<Equal<UpdateMetrics, null>>();

// Column with $updateFn omitted vs explicitly provided
db.update(Logs).set({ message: "Updated message" });
db.update(Logs).set({
  message: "Updated message",
  updatedAt: new Date("2026-01-01"),
});

// Update column with another column of compatible type
const _updateColumnValueQuery = db.update(Users).set({
  username: Users.externalId,
  email: Users.username,
});
type UpdateColumnValue = Awaited<typeof _updateColumnValueQuery>;
Expect<Equal<UpdateColumnValue, null>>();

// Update column with scalar SQL functions
const _updateScalarFnsQuery = db.update(Users).set({
  username: lower(Users.username),
  email: coalesce(Users.email, "fallback@example.com"),
});
type UpdateScalarFns = Awaited<typeof _updateScalarFnsQuery>;
Expect<Equal<UpdateScalarFns, null>>();

// Arithmetic scalar SQL functions on numeric columns
const _updateArithmeticQuery = db.update(CheckTest).set({
  quantity: add(CheckTest.quantity, 1),
});
type UpdateArithmetic = Awaited<typeof _updateArithmeticQuery>;
Expect<Equal<UpdateArithmetic, null>>();

// ============================================================================
// Section 3: Where Conditions & Filtering
// ============================================================================

// Simple equality where condition
const _updateWithWhereQuery = db
  .update(Users)
  .set({ username: "updated_user" })
  .where(eq(Users.id, 1n));
type UpdateWithWhere = Awaited<typeof _updateWithWhereQuery>;
Expect<Equal<UpdateWithWhere, null>>();

// Compound condition (and)
const _updateWithAndQuery = db
  .update(Users)
  .set({ email: "new@example.com" })
  .where(and(eq(Users.id, 1n), eq(Users.type, "admin")));
type UpdateWithAnd = Awaited<typeof _updateWithAndQuery>;
Expect<Equal<UpdateWithAnd, null>>();

// ============================================================================
// Section 4: Returning Clause Selection
// ============================================================================

// Specific column returning
const _updateReturningSpecificQuery = db
  .update(Users)
  .set({ email: "updated@example.com" })
  .returning({ id: true, email: true });
type UpdateReturningSpecific = Awaited<typeof _updateReturningSpecificQuery>;
Expect<
  Equal<UpdateReturningSpecific, { id: bigint; email: string | null }[]>
>();

// False-map returning ({ column: false }) excludes specified column
const _updateReturningFalseMapQuery = db
  .update(Users)
  .set({ username: "new_username" })
  .returning({ email: false });
type UpdateReturningFalseMap = Awaited<typeof _updateReturningFalseMapQuery>;
Expect<
  Equal<
    UpdateReturningFalseMap,
    {
      id: bigint;
      username: string;
      type: "admin" | "user";
      createdAt: Date;
      externalId: string;
      trackingId: string | null;
    }[]
  >
>();

// Single column returning
const _updateReturningSingleQuery = db
  .update(Users)
  .set({ username: "updated_user" })
  .returning({ username: true });
type UpdateReturningSingle = Awaited<typeof _updateReturningSingleQuery>;
Expect<Equal<UpdateReturningSingle, { username: string }[]>>();

// Order of returning and where (returning before where)
const _updateReturningBeforeWhereQuery = db
  .update(Users)
  .set({ username: "new_username" })
  .returning({ id: true, username: true })
  .where(eq(Users.id, 1n));
type UpdateReturningBeforeWhere = Awaited<
  typeof _updateReturningBeforeWhereQuery
>;
Expect<Equal<UpdateReturningBeforeWhere, { id: bigint; username: string }[]>>();

// Enum and $updateFn columns in returning selection
const _updateEnumReturningQuery = db
  .update(Users)
  .set({ type: "user" })
  .returning({ type: true });
type UpdateEnumReturning = Awaited<typeof _updateEnumReturningQuery>;
Expect<Equal<UpdateEnumReturning, { type: "admin" | "user" }[]>>();

const _updateLogsReturningQuery = db
  .update(Logs)
  .set({ message: "New message" })
  .returning({ id: true, message: true, updatedAt: true });
type UpdateLogsReturning = Awaited<typeof _updateLogsReturningQuery>;
Expect<
  Equal<UpdateLogsReturning, { id: bigint; message: string; updatedAt: Date }[]>
>();

// ============================================================================
// Section 5: Negative Type Safety Tests
// ============================================================================

// @ts-expect-error - Invalid enum value should not compile
db.update(Users).set({ type: "invalid_type" });

// @ts-expect-error - Wrong type for column should not compile
db.update(Users).set({ username: 123 });

// @ts-expect-error - Wrong reference type should not compile
db.update(UserProfiles).set({ userId: "invalid" });

// @ts-expect-error - Non-existent column on table should not compile
db.update(Users).set({ nonExistentColumn: "value" });

// @ts-expect-error - Mismatched $type override property should not compile
db.update(Posts).set({ metrics: { views: "not-a-number" } });

db.update(Users)
  .set({ username: "test" })
  // @ts-expect-error - Returning non-existent column should not compile
  .returning({ nonExistentColumn: true });

// @ts-expect-error - Assigning column of incompatible type (bigint -> string) should not compile
db.update(Users).set({ username: Users.id });

// @ts-expect-error - Assigning nullable column to notNull column should not compile
db.update(Users).set({ username: Users.email });

// @ts-expect-error - Assigning nullable function result to notNull column should not compile
db.update(Users).set({ username: lower(Users.email) });

// @ts-expect-error - Assigning aggregate function to set should not compile
db.update(Users).set({ username: count(Users.id) });

// @ts-expect-error - Assigning column of another table should not compile
db.update(Users).set({ username: Posts.title });

// @ts-expect-error - Assigning scalar function referencing another table should not compile
db.update(Users).set({ username: lower(Posts.title) });

// @ts-expect-error - Assigning number scalar function to bigint column should not compile
db.update(CheckTest).set({ price: add(CheckTest.price, 100n) });
