import { and, eq, type Sql, sql } from "durcno";
import { db, type Events, Logs, Posts, UserProfiles, Users } from "./schema";
import { type Equal, Expect } from "./utils";

// ============================================================================
// Section 1: Column Update Set Type Inference (Static Type Assertions)
// ============================================================================

type UsersUpdateType = Parameters<
  ReturnType<typeof db.update<typeof Users>>["set"]
>[0];

type EventsUpdateType = Parameters<
  ReturnType<typeof db.update<typeof Events>>["set"]
>[0];

type LogsUpdateType = Parameters<
  ReturnType<typeof db.update<typeof Logs>>["set"]
>[0];

// Primary key column should be excluded from update set object
Expect<Equal<"id" extends keyof UsersUpdateType ? true : false, false>>();

// Generated BY DEFAULT column should be optional and allow value | null | undefined | Sql
Expect<Equal<EventsUpdateType["autoId"], bigint | null | undefined | Sql>>();

// Not null column without default should be optional in update set
Expect<Equal<UsersUpdateType["username"], string | undefined | Sql>>();

// Not null column with default should be optional in update set
Expect<Equal<UsersUpdateType["createdAt"], Date | undefined | Sql>>();

// Default column without not null should allow value | null | undefined | Sql
Expect<
  Equal<EventsUpdateType["description"], string | null | undefined | Sql>
>();

// Nullable column without default should allow value | null | undefined | Sql
Expect<Equal<UsersUpdateType["email"], string | null | undefined | Sql>>();

// Column with $updateFn should be optional in update set
Expect<Equal<LogsUpdateType["updatedAt"], Date | undefined | Sql>>();

// ============================================================================
// Section 2: Update Query Builder & Values (.set())
// ============================================================================

// Basic update returning null
const _basicUpdateQuery = db.update(Users).set({
  username: "new_username",
  email: "new@example.com",
});
type BasicUpdate = Awaited<typeof _basicUpdateQuery>;
Expect<Equal<BasicUpdate, null>>();

// Partial update (subset of columns)
const _partialUpdateQuery = db.update(Users).set({
  email: "updated@example.com",
});
type PartialUpdate = Awaited<typeof _partialUpdateQuery>;
Expect<Equal<PartialUpdate, null>>();

// Setting nullable field to explicit null
const _nullUpdateQuery = db.update(Users).set({
  email: null,
});
type NullUpdate = Awaited<typeof _nullUpdateQuery>;
Expect<Equal<NullUpdate, null>>();

// Sql expression value in set
const _updateSqlValueQuery = db.update(Users).set({
  username: sql`LOWER(first_name)`,
});
type UpdateSqlValue = Awaited<typeof _updateSqlValueQuery>;
Expect<Equal<UpdateSqlValue, null>>();

// Column with $type override in set
const _updateMetricsQuery = db.update(Posts).set({
  metrics: { views: 200, likes: 100 },
});
type UpdateMetrics = Awaited<typeof _updateMetricsQuery>;
Expect<Equal<UpdateMetrics, null>>();

// Column with $updateFn omitted vs explicitly provided
db.update(Logs).set({ message: "Updated message" });
db.update(Logs).set({
  message: "Updated message",
  updatedAt: new Date("2026-01-01"),
});

// ============================================================================
// Section 3: Where Conditions & Filtering
// ============================================================================

// Simple equality where condition
const _updateWithWhereQuery = db
  .update(Users)
  .set({ username: "updated_user" })
  .where(eq(Users.id, 1n));
type UpdateWithWhere = Awaited<typeof _updateWithWhereQuery>;
Expect<Equal<UpdateWithWhere, null>>();

// Compound condition (and)
const _updateWithAndQuery = db
  .update(Users)
  .set({ email: "new@example.com" })
  .where(and(eq(Users.id, 1n), eq(Users.type, "admin")));
type UpdateWithAnd = Awaited<typeof _updateWithAndQuery>;
Expect<Equal<UpdateWithAnd, null>>();

// ============================================================================
// Section 4: Returning Clause Selection
// ============================================================================

// Specific column returning
const _updateReturningSpecificQuery = db
  .update(Users)
  .set({ email: "updated@example.com" })
  .returning({ id: true, email: true });
type UpdateReturningSpecific = Awaited<typeof _updateReturningSpecificQuery>;
Expect<
  Equal<UpdateReturningSpecific, { id: bigint; email: string | null }[]>
>();

// False-map returning ({ column: false }) excludes specified column
const _updateReturningFalseMapQuery = db
  .update(Users)
  .set({ username: "new_username" })
  .returning({ email: false });
type UpdateReturningFalseMap = Awaited<typeof _updateReturningFalseMapQuery>;
Expect<
  Equal<
    UpdateReturningFalseMap,
    {
      id: bigint;
      username: string;
      type: "admin" | "user";
      createdAt: Date;
      externalId: string;
      trackingId: string | null;
    }[]
  >
>();

// Single column returning
const _updateReturningSingleQuery = db
  .update(Users)
  .set({ username: "updated_user" })
  .returning({ username: true });
type UpdateReturningSingle = Awaited<typeof _updateReturningSingleQuery>;
Expect<Equal<UpdateReturningSingle, { username: string }[]>>();

// Order of returning and where (returning before where)
const _updateReturningBeforeWhereQuery = db
  .update(Users)
  .set({ username: "new_username" })
  .returning({ id: true, username: true })
  .where(eq(Users.id, 1n));
type UpdateReturningBeforeWhere = Awaited<
  typeof _updateReturningBeforeWhereQuery
>;
Expect<Equal<UpdateReturningBeforeWhere, { id: bigint; username: string }[]>>();

// Enum and $updateFn columns in returning selection
const _updateEnumReturningQuery = db
  .update(Users)
  .set({ type: "user" })
  .returning({ type: true });
type UpdateEnumReturning = Awaited<typeof _updateEnumReturningQuery>;
Expect<Equal<UpdateEnumReturning, { type: "admin" | "user" }[]>>();

const _updateLogsReturningQuery = db
  .update(Logs)
  .set({ message: "New message" })
  .returning({ id: true, message: true, updatedAt: true });
type UpdateLogsReturning = Awaited<typeof _updateLogsReturningQuery>;
Expect<
  Equal<UpdateLogsReturning, { id: bigint; message: string; updatedAt: Date }[]>
>();

// ============================================================================
// Section 5: Negative Type Safety Tests
// ============================================================================

// @ts-expect-error - Invalid enum value should not compile
db.update(Users).set({ type: "invalid_type" });

// @ts-expect-error - Wrong type for column should not compile
db.update(Users).set({ username: 123 });

// @ts-expect-error - Wrong reference type should not compile
db.update(UserProfiles).set({ userId: "invalid" });

// @ts-expect-error - Non-existent column on table should not compile
db.update(Users).set({ nonExistentColumn: "value" });

// @ts-expect-error - Mismatched $type override property should not compile
db.update(Posts).set({ metrics: { views: "not-a-number" } });

db.update(Users)
  .set({ username: "test" })
  // @ts-expect-error - Returning non-existent column should not compile
  .returning({ nonExistentColumn: true });
